version: "3.8"
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - "5563:5432"
    volumes:
      - ./build_db.sql:/docker-entrypoint-initdb.d/scripts.sql