version: "3.8"
services:
  api1:
    build: .
    working_dir: /app
    volumes:
      - ./:/app

    ports:
      - "8080"

    depends_on:
      - db

    networks:
      - my-network

    command: ["sbt", "clean", "run"]

    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '1GB'

  api2:
    build: .
    working_dir: /app
    volumes:
      - ./:/app

    ports:
      - "8080"

    depends_on:
      - db

    networks:
      - my-network

    command: [ "sbt", "clean", "run"]

    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '1GB'

  lb:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '500MB'

    networks:
      - my-network

  db:
    image: postgres

    command:
      [ "postgres", "-c", "config_file=/etc/postgresql/postgresql.conf" ]

    restart: always

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin

    ports:
      - "5563:5432"

    volumes:
      - ./build_db.sql:/docker-entrypoint-initdb.d/scripts.sql
      - ./postgresql.conf:/etc/postgresql/postgresql.conf

    networks:
      - my-network

networks:
  my-network: